# TODO: Update with exact module version
name: yoloxtrain
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.8
  # Pytorch
  - pytorch==1.12.1
  - torchvision==0.13.1
  - cudatoolkit==11.3.1
  - cudnn==8.2.1
  # Pip
  - pip
  - pip:
    - numpy==1.23.4
    - opencv_python==4.6.0.66
    - loguru==0.6.0
    - tqdm==4.64.1
    - thop
    - ninja==1.10.2.4
    - tabulate==0.9.0
    # replace with 'pycocotools' on linux
    - pycocotools-windows==2.0.0.2
    - onnx==1.8.1
    - onnxruntime==1.8.0
    - onnx-simplifier==0.3.5
    - tensorboard==2.10.1
    - wandb==0.13.4